title: Ting Turn Up
author: Chris Hollins
email: topher1397@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you see my cortex in data form. Hopefully I capture some of you viewers interest with my love for music, art, or just free spirit.
# social links
twitter_username: TophBaby
github_username:  TophHollins

show_excerpts: true # set to false to remove excerpts on the homepage
